server:
  port: 9060
  mode: release
  read_timeout: 60   # 读取超时时间，单位秒
  write_timeout: 60  # 写入超时时间，单位秒
  limit_num: 100     # 限流数（每秒请求数）

database:
  host: ${DB_HOST}
  port: 5432
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  dbname: ${DB_NAME}
  sslmode: require     # SSL 模式，require 表示要求使用 SSL 连接
  max_idle_conns: 10   # 最大空闲连接数
  max_open_conns: 100  # 最大打开连接数
  max_lifetime: 3600   # 连接的最大生命周期，单位秒；0 表示不限制生命周期；超过这个时间后连接会被关闭并重新建立
  log_level: error     # 数据库日志级别，error 表示只记录错误日志
  auto_migrate: false  # 是否自动迁移数据库表结构（即启动程序时会自动在数据库中创建表）
redis:
  addr: ${REDIS_ADDR}
  password: ${REDIS_PASSWORD}
  db: 0              # Redis 数据库编号（0-15）
  pool_size: 20      # 连接池大小
  min_idle_conns: 10 # 最小空闲连接数，保持至少 10 个空闲连接在连接池中
  max_retries: 3     # 最大重试次数

log:
  level: info
  file_path: /var/log/gin-app/app.log
  max_size: 100      # 日志文件最大大小，单位 MB
  max_age: 30        # 日志文件最大保存时间，单位天


# 维度	    http_only	        secure
# 作用对象	浏览器 JavaScript  网络传输协议
# 保护目标	防止客户端脚本窃取	防止网络窃听
# 实现层面	Cookie 属性标志	   Cookie 属性标志
session:
  key: gin-session   # 会话 Cookie 的名称：在浏览器中存储的 Cookie 名称
  max_age: 604800    # 会话过期时间，单位秒；即7天
  path: /            # Cookie 的有效路径：/ 表示对整个网站有效
  domain: ""         # Cookie 的有效域名：空字符串表示当前域名
  http_only: true    # HTTP Only 标志：true 表示 Cookie 只能通过 HTTP 协议访问，不能通过 JavaScript 访问；控制访问层面：浏览器层面
  secure: true       # Secure 标志：true 表示 Cookie 只能通过 HTTPS 加密连接传输；控制访问层面：网络传输层面

